export const ActionTypes = {
  FETCH_COORDINATES: 'FETCH_COORDINATES',
  FETCH_FULL_WEATHER_INFO: 'FETCH_FULL_WEATHER_INFO',
  FETCH_PREVIOUS_DAY_INFO: 'FETCH_PREVIOUS_DAY_INFO',
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  SET_METRICS_FORM_DATA: 'SET_METRICS_FORM_DATA',
  ADD_METRICS: 'ADD_METRICS',
  SET_CLASS_ATTR: 'SET_CLASS_ATTR'
};